package msgpack

// Auto-generated by internal/cmd/gencontainer/gencontainer.go. DO NOT EDIT!

import "github.com/pkg/errors"

func (enl *encoderNL) encodeMapBool(in interface{}) error {
	for k, v := range in.(map[string]bool) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapInt(in interface{}) error {
	for k, v := range in.(map[string]int) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapInt8(in interface{}) error {
	for k, v := range in.(map[string]int8) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapInt16(in interface{}) error {
	for k, v := range in.(map[string]int16) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapInt32(in interface{}) error {
	for k, v := range in.(map[string]int32) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapInt64(in interface{}) error {
	for k, v := range in.(map[string]int64) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapUint(in interface{}) error {
	for k, v := range in.(map[string]uint) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapUint8(in interface{}) error {
	for k, v := range in.(map[string]uint8) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapUint16(in interface{}) error {
	for k, v := range in.(map[string]uint16) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapUint32(in interface{}) error {
	for k, v := range in.(map[string]uint32) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapUint64(in interface{}) error {
	for k, v := range in.(map[string]uint64) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapFloat32(in interface{}) error {
	for k, v := range in.(map[string]float32) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapFloat64(in interface{}) error {
	for k, v := range in.(map[string]float64) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeMapString(in interface{}) error {
	for k, v := range in.(map[string]string) {
		if err := enl.EncodeString(k); err != nil {
			return errors.Wrap(err, `failed to encode key`)
		}
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for %s`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayBool(in interface{}) error {
	for k, v := range in.([]bool) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayInt(in interface{}) error {
	for k, v := range in.([]int) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayInt8(in interface{}) error {
	for k, v := range in.([]int8) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayInt16(in interface{}) error {
	for k, v := range in.([]int16) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayInt32(in interface{}) error {
	for k, v := range in.([]int32) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayInt64(in interface{}) error {
	for k, v := range in.([]int64) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayUint(in interface{}) error {
	for k, v := range in.([]uint) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayUint8(in interface{}) error {
	for k, v := range in.([]uint8) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayUint16(in interface{}) error {
	for k, v := range in.([]uint16) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayUint32(in interface{}) error {
	for k, v := range in.([]uint32) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayUint64(in interface{}) error {
	for k, v := range in.([]uint64) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayFloat32(in interface{}) error {
	for k, v := range in.([]float32) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayFloat64(in interface{}) error {
	for k, v := range in.([]float64) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}

func (enl *encoderNL) encodeArrayString(in interface{}) error {
	for k, v := range in.([]string) {
		if err := enl.Encode(v); err != nil {
			return errors.Wrapf(err, `failed to encode value for element %d`, k)
		}
	}
	return nil
}
